# Generated by Django 4.0.3 on 2022-03-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
